#!/usr/bin/env bash
# =============================================================================
# vLLM GB10 Installer
# Installs and patches vLLM for NVIDIA DGX Spark GB10 (ARM aarch64, sm_121)
# =============================================================================
set -euo pipefail

# -- Colors ------------------------------------------------------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*"; }
die()   { err "$*"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$HOME/vllm-env"
NCCL_DIR="$HOME/nccl"
NCCL_VERSION="v2.28.9-1"
VLLM_VERSION="0.18.1"
PYTHON="python3.12"

# -- Pre-flight checks -------------------------------------------------------

info "Checking platform..."

ARCH="$(uname -m)"
if [[ "$ARCH" != "aarch64" ]]; then
    warn "Architecture is $ARCH, not aarch64. This installer is designed for DGX Spark GB10."
    read -rp "Continue anyway? [y/N] " ans
    [[ "$ans" =~ ^[Yy] ]] || exit 0
fi

if command -v nvidia-smi &>/dev/null; then
    GPU_NAME="$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 || echo "unknown")"
    info "Detected GPU: $GPU_NAME"
else
    warn "nvidia-smi not found. Ensure CUDA 13.0 is installed."
fi

if ! command -v "$PYTHON" &>/dev/null; then
    die "Python 3.12 not found. Install with: sudo apt install python3.12 python3.12-venv python3.12-dev"
fi

if ! dpkg -s python3.12-dev &>/dev/null 2>&1; then
    warn "python3.12-dev not found. Installing (required for Triton compilation)..."
    sudo apt update && sudo apt install -y python3.12-dev
fi

# -- System dependencies -----------------------------------------------------

info "Installing system dependencies..."
sudo apt update -qq
sudo apt install -y -qq build-essential git python3.12-venv python3.12-dev

# -- Virtual environment ------------------------------------------------------

if [[ -d "$VENV_DIR" ]]; then
    info "Virtual environment already exists at $VENV_DIR"
    read -rp "Recreate it? [y/N] " ans
    if [[ "$ans" =~ ^[Yy] ]]; then
        rm -rf "$VENV_DIR"
        $PYTHON -m venv "$VENV_DIR"
        ok "Created fresh virtualenv at $VENV_DIR"
    fi
else
    info "Creating virtual environment at $VENV_DIR..."
    $PYTHON -m venv "$VENV_DIR"
    ok "Created virtualenv at $VENV_DIR"
fi

source "$VENV_DIR/bin/activate"

# -- Install vLLM + dependencies ---------------------------------------------

info "Upgrading pip..."
pip install --upgrade pip setuptools wheel -q

info "Installing vLLM $VLLM_VERSION..."
pip install "vllm==$VLLM_VERSION" -q

info "Installing aligned package versions..."
pip install "triton==3.6.0" "transformers==4.57.6" -q

ok "vLLM $VLLM_VERSION installed"

# -- Apply CUTLASS FP8 patch (Fix 5) -----------------------------------------

info "Applying CUTLASS FP8 patch for sm_121..."
bash "$SCRIPT_DIR/patches/cutlass-fp8-sm121.patch"
ok "CUTLASS FP8 patch applied"

# -- Build NCCL from source (Fix 1) ------------------------------------------

if [[ -f "$NCCL_DIR/build/lib/libnccl.so" ]]; then
    info "NCCL custom build already exists at $NCCL_DIR/build/lib/"
    read -rp "Rebuild NCCL? [y/N] " ans
    if [[ "$ans" =~ ^[Yy] ]]; then
        bash "$SCRIPT_DIR/scripts/build-nccl-sm121.sh"
    else
        info "Skipping NCCL build"
    fi
else
    info "Building NCCL from source for sm_121..."
    bash "$SCRIPT_DIR/scripts/build-nccl-sm121.sh"
fi

# -- Configure Ray memory threshold (Fix 7) ----------------------------------

info "Configuring Ray for unified memory..."
bash "$SCRIPT_DIR/patches/ray-memory-threshold.sh"
ok "Ray memory threshold configured"

# -- Set up environment profile -----------------------------------------------

ENV_PROFILE="$HOME/.vllm-gb10-env"

info "Writing environment profile to $ENV_PROFILE..."

cat > "$ENV_PROFILE" << 'ENVEOF'
# vLLM GB10 environment -- source this before running vLLM
# Generated by vllm-gb10 installer

# Activate virtualenv
source ~/vllm-env/bin/activate

# Custom NCCL (must come first in LD_LIBRARY_PATH)
NCCL_LIB="$HOME/nccl/build/lib"
CUDA_RUNTIME_LIB="$(python -c 'import nvidia.cuda_runtime; import os; print(os.path.join(os.path.dirname(nvidia.cuda_runtime.__file__), "lib"))' 2>/dev/null || echo "")"

export LD_LIBRARY_PATH="${NCCL_LIB}:${CUDA_RUNTIME_LIB}:/usr/local/cuda/lib64:${LD_LIBRARY_PATH:-}"

# NCCL settings for multi-node (harmless on single-node)
export NCCL_SOCKET_IFNAME=enp1s0f0np0
export UCX_NET_DEVICES=enp1s0f0np0
export NCCL_NET_GDR_LEVEL=SYS
export NCCL_P2P_DISABLE=1
export NCCL_IB_DISABLE=1

# Ray unified memory fix
export RAY_memory_usage_threshold=1.0

# Offline mode (set HF_HUB_OFFLINE=1 if models are pre-downloaded)
# export HF_HUB_OFFLINE=1
ENVEOF

ok "Environment profile written to $ENV_PROFILE"

# -- Verify installation ------------------------------------------------------

info "Running verification..."
bash "$SCRIPT_DIR/scripts/verify-install.sh"

# -- Done ---------------------------------------------------------------------

echo ""
echo -e "${GREEN}=========================================${NC}"
echo -e "${GREEN}  vLLM GB10 installation complete!${NC}"
echo -e "${GREEN}=========================================${NC}"
echo ""
echo "To use vLLM, source the environment first:"
echo ""
echo "  source $ENV_PROFILE"
echo ""
echo "Then launch a model:"
echo ""
echo "  vllm serve /path/to/model --trust-remote-code --enforce-eager"
echo ""
echo "For multi-node setup, see configs/multi-node-head.env and configs/multi-node-worker.env"
echo ""
