#!/usr/bin/env bash
# =============================================================================
# QSFP 200GbE Network Configuration for DGX Spark GB10
#
# Configures QSFP direct-connect interfaces with MTU 9000 (jumbo frames)
# for efficient NCCL tensor transfers between nodes.
#
# Usage:
#   sudo ./setup-qsfp.sh [QSFP_IP] [QSFP_IP_SECONDARY]
#
# Examples:
#   sudo ./setup-qsfp.sh 192.168.100.10              # Head node
#   sudo ./setup-qsfp.sh 192.168.100.11              # Worker node
#   sudo ./setup-qsfp.sh 192.168.100.10 192.168.200.10  # Both interfaces
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/common.sh"

if [[ $EUID -ne 0 ]]; then
    die "This script must be run as root (sudo)"
fi

# Validate IPv4 address format to prevent injection into netplan YAML
validate_ip() {
    local ip="$1"
    if [[ ! "$ip" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        die "Invalid IP address: $ip"
    fi
    # Verify each octet is 0-255
    local IFS='.'
    read -ra octets <<< "$ip"
    for octet in "${octets[@]}"; do
        if (( octet > 255 )); then
            die "Invalid IP address (octet > 255): $ip"
        fi
    done
}

# Auto-detect QSFP interfaces (typically enp*np* pattern on DGX Spark)
detect_qsfp_interfaces() {
    local interfaces=()
    for iface in /sys/class/net/enp*np*; do
        [[ -e "$iface" ]] && interfaces+=("$(basename "$iface")")
    done

    if [[ ${#interfaces[@]} -eq 0 ]]; then
        # Fallback: look for any interface with 200Gbps speed
        for iface in /sys/class/net/*/speed; do
            speed="$(cat "$iface" 2>/dev/null || echo 0)"
            if [[ "$speed" -ge 100000 ]]; then
                interfaces+=("$(basename "$(dirname "$iface")")")
            fi
        done
    fi

    echo "${interfaces[@]}"
}

QSFP_INTERFACES=($(detect_qsfp_interfaces))

if [[ ${#QSFP_INTERFACES[@]} -eq 0 ]]; then
    die "No QSFP interfaces detected. Expected interfaces matching enp*np* pattern."
fi

info "Detected QSFP interfaces: ${QSFP_INTERFACES[*]}"

PRIMARY="${QSFP_INTERFACES[0]}"
SECONDARY="${QSFP_INTERFACES[1]:-}"

QSFP_IP_PRIMARY="${1:-}"
QSFP_IP_SECONDARY="${2:-}"

if [[ -n "$QSFP_IP_PRIMARY" ]]; then
    validate_ip "$QSFP_IP_PRIMARY"
fi
if [[ -n "$QSFP_IP_SECONDARY" ]]; then
    validate_ip "$QSFP_IP_SECONDARY"
fi

if [[ -z "$QSFP_IP_PRIMARY" ]]; then
    echo ""
    echo "Usage: sudo $0 <PRIMARY_QSFP_IP> [SECONDARY_QSFP_IP]"
    echo ""
    echo "Detected interfaces:"
    echo "  Primary:   $PRIMARY"
    [[ -n "$SECONDARY" ]] && echo "  Secondary: $SECONDARY"
    echo ""
    echo "Example for head node:   sudo $0 192.168.100.10 192.168.200.10"
    echo "Example for worker node: sudo $0 192.168.100.11 192.168.200.11"
    exit 1
fi

# Generate netplan config
NETPLAN_FILE="/etc/netplan/01-qsfp.yaml"

info "Writing netplan config to $NETPLAN_FILE..."

cat > "$NETPLAN_FILE" << EOF
# QSFP 200GbE configuration for DGX Spark GB10
# Generated by vllm-gb10/scripts/setup-qsfp.sh
network:
  version: 2
  ethernets:
    $PRIMARY:
      addresses:
        - ${QSFP_IP_PRIMARY}/24
      mtu: 9000
EOF

if [[ -n "$SECONDARY" && -n "$QSFP_IP_SECONDARY" ]]; then
    cat >> "$NETPLAN_FILE" << EOF
    $SECONDARY:
      addresses:
        - ${QSFP_IP_SECONDARY}/24
      mtu: 9000
EOF
fi

info "Validating netplan configuration..."
if ! netplan generate 2>&1; then
    die "Netplan validation failed. Check $NETPLAN_FILE for errors."
fi

info "Applying netplan configuration..."
netplan apply

ok "QSFP network configured:"
echo "  Interface: $PRIMARY -> ${QSFP_IP_PRIMARY}/24 (MTU 9000)"
[[ -n "$SECONDARY" && -n "$QSFP_IP_SECONDARY" ]] && \
    echo "  Interface: $SECONDARY -> ${QSFP_IP_SECONDARY}/24 (MTU 9000)"

echo ""
echo "Verify connectivity with:"
echo "  ping -M do -s 8972 <PEER_QSFP_IP>"
echo ""
echo "A successful result confirms MTU 9000 jumbo frames are working."
